apiVersion: v1
entries:
  sample-elk:
  - apiVersion: v1
    created: 2017-06-05T17:19:08.799961993-04:00
    description: Microservice Builder ELK Sample
    digest: f46af02047ef412aa7d9ee75d865b0a7d70adc53b00e604bd1c97249ecd82898
    icon: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/microservicebuilder/icon.png
    name: sample-elk
    urls:
    - https://fahhamk.github.io/sample-elk/charts/sample-elk-0.1.0.tgz
    version: 0.1.0
generated: 2017-06-05T17:19:08.799287227-04:00
